version: 2
registries:
  maven-repository-wooga-jfrog-io-wooga-atlas-maven:
    type: maven-repository
    url: https://wooga.jfrog.io/wooga/atlas-maven
    username: atlas
    password: "${{secrets.MAVEN_REPOSITORY_WOOGA_JFROG_IO_WOOGA_ATLAS_MAVEN_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.spockframework:spock-core
    versions:
    - ">= 0"
  - dependency-name: net.wooga.plugins
    versions:
    - 1.5.0
    - 2.0.0
  - dependency-name: com.gradle.plugin-publish
    versions:
    - 0.13.0
    - 0.14.0
  - dependency-name: com.netflix.nebula:nebula-test
    versions:
    - 7.10.2
    - 8.1.0
  - dependency-name: org.kt3k.gradle.plugin:coveralls-gradle-plugin
    versions:
    - 2.8.3
  registries:
  - maven-repository-wooga-jfrog-io-wooga-atlas-maven
